sudo: false
language: go
go:
    - 1.11.x
    - 1.12.x
    - master

go_import_path: m0x.ru/s/albr

install:
    - go get -t -v ./...

script:
    - go test -v -race ./...

matrix:
    allow_failures:
       - go: master
    fast_finish: true
